spring:
    #profiles:
      #active: prod
    thymeleaf:
       cache: false 
       prefix: classpath:/templates/
       encoding: UTF-8
       suffix: .html
       mode: LEGACYHTML5

    datasource:
      data1:
        jdbcUrl: jdbc:sqlite:database.sqlite?date_string_format=yyyy-MM-dd hh:mm:ss
        driver-class-name: org.sqlite.JDBC
        username: root
        password: root123456
    servlet:
      multipart:
        # 单个文件最大大小
        max-file-size: 50MB
        # 所有上传文件最大大小
        max-request-size: 50MB

server:
  port: 8080
logging:
     config: classpath:logback.xml
wx:
   pay:
#应用id（小程序id）
      appId: wx97d67597e297e046
      secret: 55881c8012ca76f9ee60dbc22968c837
      merchantId: 1xxxxxxxxx
      privateKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      merchantSerialNumber: 315DDXXXXXXXXXXXXXXXXXXXXXXXXXXX
      apiV3Key: XXXXXXXXXXXXXXXXXXXXXXXXXX
      payNotifyUrl: https://xxx.xxxx.xxx.xxx/xx/xxxx/xxxx/openapi/wx/payNotify
      refundNotifyUrl: https://xxx.xxx.xxx.xxx/xxxx/xxxx/xxxx/openapi/wx/refundNotify

